### PR TITLE
Fixed assembly number for Glimpse.Ado

### PR DESCRIPTION
**Pull request by sorenhl**

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Thanks for this! If you want to update the nuspec as well feel free. Its just [this](https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.Ado.Net45/NuSpec/Glimpse.Ado.nuspec#L18) line that needs a description updated for what was fixed.

**Comment by avanderhoorn** [comment]
@sorenhl Just wondering if you have had a chance to look at this?

**Comment by sorenhl** [comment]
Hi avanderhoorn, I am on holiday without my laptop, but can you change it? The Text should state "Fixed null-pointer exception that occoured when using transactions without commands"

**Comment by avanderhoorn** [comment]
No worries, just wanted to give you a chance to do it if you wanted to :)

**Pull request merged**
