### PR TITLE
Fixed NRE crash with the AspNet caching code. 

### PR DESCRIPTION
**Pull request by kendallb**
Fixes this issue:

https://github.com/Glimpse/Glimpse/issues/1001

### CODE REVIEW

**Comment by jrmoreno1** [comment]
@kendallb: just curious if the CLA has anything to do with why this wasn't merged?

**Comment by kendallb** [comment]
Entirely possible. I will execute the CLA now.

**Comment by kendallb** [comment]
All good now for someone to merge it :) Been using my own build for 3 years now. lol.

**Comment by jrmoreno1** [comment]
@avanderhoorn : review?

**Pull request closed without merging**
