### PR TITLE
fixed issue #651 - Keyboard Shortcuts

### PR DESCRIPTION
**Pull request by samranjbari**
+ Modified the Glimpse.axd to allow for disabling the shortcut keys. The checkbox is placed under more details link

+ Implemented the keys below
var shortcutKeys = {
        Maximize: '103', // G
        Minimize: '103',  // G (toggle)
        Popup:    '112',   // P
        Help:     '63',       // ?
        Close:    '120',     // X 
    }

### CODE REVIEW

**Comment by avanderhoorn** [comment]
@samranjbari This is looking great! Sorry for the delay in getting back to this, got a new baby and been taking time out. Just wondering what browsers you have tested on? Also I'm afraid to say that the changes for the `glimpse.js` need to go over here - https://github.com/glimpse/glimpse.client/. Hopefully this will be a bit easier to work with. To build the client, assuming you have node installed, you just need to run `node make`. Really great effort and looking forward to getting this in!

**Comment by samranjbari** [comment]
@avanderhoorn Congrats on the baby!!  I tested on IE8>, chrome and FF all windows through browserstack. I can do more testing if needed.
I'll look into moving the changes.

**Comment by avanderhoorn** [comment]
Thanks for letting me know about the tests. Sounds like more than we need ;) and appreciate you getting the change back into the client. I've gotten the release ready to go otherwise (5630c5e219d2bd708c83d5a16b26d9bafe92b3a8). After that, all that is left is if you could sign the [CLA](https://www.dropbox.com/s/z9abe8y9mr7r7rv/Glimpse%20Project%20Individual%20Contributor%20License%20Agreement.docx) and send it to me at anthony.vanderhoorn at the google place.

**Comment by samranjbari** [comment]
@avanderhoorn moved the changes to Glimpse.Client and requested a pulled.

**Comment by avanderhoorn** [comment]
Great stuff!!! As soon as I get the CLA I'll get this in and the release out... currently working on the release notes, etc.

**Comment by avanderhoorn** [comment]
Found an issue in testing. When you are focused in a input and type any of the targeted keys, they come into effect. This means that when typing something like "gaggle of geese?", all sorts of things start to happen. This means we probably need to make it a combination key or know when any input is focused.

**Comment by avanderhoorn** [comment]
We probably need to use a method like this - http://jsfiddle.net/bM6uY/4/:
```
$(document).bind('keypress', function(event) {
    if( event.which === 65 && event.shiftKey ) {
        alert('you pressed SHIFT+A');
    }
});
```

**Comment by samranjbari** [comment]
I thought that was the purpose of the disable shortcut keys option. So they can disable the option in case of form controls.
What if they need to type upper case G in their text box? wouldn't this snippet still run?

**Comment by avanderhoorn** [comment]
With the exact sample I provided yes :) but we could use `cntr` or `alt`? Using either of these means that it would only be a problem if they had something that used those exact control combination... they shouldn't come across that problem in normal typing.

**Comment by samranjbari** [comment]
ok, I will update the key mapping

**Comment by avanderhoorn** [comment]
Thanks!

**Comment by avanderhoorn** [comment]
Just wondering if you have had any luck with this? Its the last thing we are waiting on before being able to release.

**Comment by samranjbari** [comment]
I'll get on this weekend. Thanks for checking in

**Comment by avanderhoorn** [comment]
Really appreciate it!

**Pull request merged**
